In [2]:
import numpy as np

# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Replace all the elements in the third column with 1
array[:, 2] = 1
print("Modified array:")
print(array)

Original array:
[[ 6 19  4 20  3]
 [18 19 20  5 14]
 [ 7 14 20  1 19]
 [11 16 15  8 12]
 [ 3  9  2 14 19]]
Modified array:
[[ 6 19  1 20  3]
 [18 19  1  5 14]
 [ 7 14  1  1 19]
 [11 16  1  8 12]
 [ 3  9  1 14 19]]


In [3]:
arr = np.array([1,2,3,4])


In [4]:
print(arr.size)

4
